spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.jad.localhost/realms/jad-dev
          jwk-set-uri: http://keycloak.jad-auth.svc.cluster.local/realms/jad-dev/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    org.springframework: DEBUG
