apiVersion: v1
kind: Service
metadata:
  name: file-sharing-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: file-sharing-app
  ports:
    - name: http
      port: 8080
      targetPort: http
